### ISSUE TITLE
dependencies dosent work or i can update or remove or fix some dependencies errors 

### ISSUE THREAD

**Issue by Mtechsin** [RedaAmrGad/S4League-Emulator#1]
![dependencies ](https://user-images.githubusercontent.com/56131987/93723107-155b5b00-fb9c-11ea-85fd-834fc051645b.png)
i dont know why but i think you can help me brother

**Comment by RedaAmrGad** [comment]
Just make a nuget restore to restore the packages

**Comment by Mtechsin** [comment]
thank you
